# Performing Principal Component Analysis (PCA) - Lab

## Introduction

Now that you have high level overview of PCA as well as some of the details in the algorithm itself, its time to practice implementing PCA on your own using the NumPy package. 

## Objectives

You will be able to:
    
* Implement PCA from scratch using NumPy

## Import the Data

To start, import the data stored in the file 'foodusa.csv'.

In [1]:
#Your code here
import pandas as pd

df = pd.read_csv('foodusa.csv')
df.head()

        City  Bread  Burger  Milk  Oranges  Tomatoes
0    ATLANTA   24.5    94.5  73.9     80.1      41.6
1  BALTIMORE   26.5    91.0  67.5     74.6      53.3
2     BOSTON   29.7   100.8  61.4    104.0      59.6
3    BUFFALO   22.8    86.6  65.3    118.4      51.2
4    CHICAGO   26.7    86.7  62.7    105.9      51.2

## Normalize the Data

Next, normalize your data by subtracting the feature mean from each of the columns

In [2]:
#Your code here
features = df.iloc[:,1:]

    Bread  Burger  Milk  Oranges  Tomatoes
0    24.5    94.5  73.9     80.1      41.6
1    26.5    91.0  67.5     74.6      53.3
2    29.7   100.8  61.4    104.0      59.6
3    22.8    86.6  65.3    118.4      51.2
4    26.7    86.7  62.7    105.9      51.2
5    25.3   102.5  63.3     99.3      45.6
6    22.8    88.8  52.4    110.9      46.8
7    23.3    85.5  62.5    117.9      41.8
8    24.1    93.7  51.5    109.7      52.4
9    29.3   105.9  80.2    133.2      61.7
10   22.3    83.6  67.8    108.6      42.4
11   26.1    88.9  65.4    100.9      43.2
12   26.9    89.3  56.2     82.7      38.4
13   20.3    89.6  53.8    111.8      53.9
14   24.6    92.2  51.9    106.0      50.7
15   30.8   110.7  66.0    107.3      62.6
16   24.5    92.3  66.7     98.0      61.7
17   26.2    95.4  60.2    117.1      49.3
18   26.5    92.4  60.8    115.1      46.2
19   25.5    83.7  57.0     92.8      35.4
20   26.3    87.1  58.3    101.8      41.5
21   22.5    77.7  62.0     91.1      44.9
22   24.2    93.8  66.0     81.6      46.2

## Calculate the Covariance Matrix

The next step for PCA is to calculate to covariance matrix for your normalized data. Do so here.

In [ ]:
#Your code here

## Calculate the Eigenvectors

Next, calculate the eigenvectors for your covariance matrix.

In [ ]:
#Your code here

## Sorting the Eigenvectors to Determine Primary Components

Great! Now that you have the eigenvectors and their associated eigenvalues, sort the eigenvectors based on their eigenvalues!

In [ ]:
#Your code here

## Reprojecting the Data

Finally, reproject the dataset using your eigenvectors. Reproject the dataset down to 2 dimensions.

In [ ]:
#Your code here

## Summary

Well done! You've now coded PCA on your own using NumPy! With that, it's time to look at further application of PCA.